const fs = require("fs");
const yaml = require("js-yaml");

/**
 * Emit the replacements YAML in the shape consumed by upstream config-replacer.js.
 *
 * Input shape:
 *   [
 *     { filename: "global-config.yaml", items: [{ pattern, replacement }, ...] },
 *     ...,
 *     { _postActions: [{ type: "removeFile", files: [...] }] }   // optional
 *   ]
 *
 * Output: top-level YAML list. postActions entry (if present) emitted as:
 *   - postActions:
 *       - type: removeFile
 *         files: [...]
 */
function emitReplacements(outPath, fileEntries) {
  const doc = [];
  for (const entry of fileEntries) {
    if (entry._postActions) {
      doc.push({ postActions: entry._postActions });
    } else {
      doc.push({ filename: entry.filename, items: entry.items });
    }
  }

  const header =
    "# Generated by lzaucreplgen. Review before use.\n" +
    "# Apply with upstream config-replacer.js.\n";
  const body = yaml.dump(doc, { lineWidth: -1, noRefs: true });
  fs.writeFileSync(outPath, header + body, "utf8");
}

function emitAdminReport(outPath, adminChanges, warnings) {
  const lines = [];
  lines.push("# Admin changes (not in replacements file)");
  lines.push("");
  lines.push(
    "These values look administrative (emails, account IDs, placeholder-marked settings)."
  );
  lines.push(
    "They are **not** emitted into the replacements file. Capture them separately —"
  );
  lines.push(
    "typically via `replacements-config.yaml` globalReplacements or environment-driven scripts."
  );
  lines.push("");

  if (adminChanges.length === 0) {
    lines.push("_No admin changes detected._");
  } else {
    const byFile = {};
    for (const c of adminChanges) {
      (byFile[c.rel] = byFile[c.rel] || []).push(c);
    }
    for (const [rel, changes] of Object.entries(byFile)) {
      lines.push(`## ${rel}`);
      lines.push("");
      for (const c of changes) {
        lines.push("**template:**");
        lines.push("```");
        lines.push(c.from);
        lines.push("```");
        lines.push("**configured:**");
        lines.push("```");
        lines.push(c.to);
        lines.push("```");
        lines.push("");
      }
    }
  }

  if (warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");
    for (const w of warnings) lines.push(`- ${w}`);
  }

  fs.writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
}

module.exports = { emitReplacements, emitAdminReport };
